@startuml

left to right direction

package task {
    (new task)
    (start task)
    (stop task)
    (complete task)
    (close task)
}

actor User as U
U --> (new task)
U --> (start task)
U --> (stop task)
U --> (complete task)
U --> (close task)

@enduml
