@startuml
title Task 状態遷移図

[*] -> Opened

state Closed {
}

state Opened {
    state Todo {
    }
    state Assigned {
        state Doing
        state Paused
        state Completed

        [*] --> Doing
        Doing --> Paused
        Paused --> Doing
        Doing --> Completed
        Completed --> Doing
        Paused --> Completed
        Completed --> Paused
    }
    [*] --> Todo
    Todo --> Assigned: member assigned
    Assigned --> Todo: member unassigned
}

Opened --> Closed: closed
Closed --> Opened: reopened
Closed --> [*]

@enduml
